version: '3.8'

services:
  front-end:
    build: ./front-end
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}"
    depends_on:
      - back-end

  back-end:
    build: ./back-end
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./local.db}
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app