version: '3.8'

services:
  front-end:
    build:
      target: development  # Forzar etapa de desarrollo
    command: npm run dev  # Sobrescribe el CMD del Dockerfile
    ports:
      - "5173:5173"  # Mapea el puerto de Vite
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000