version: '3.8'

services:
  front-end:
    build:
      args:
        NODE_ENV: production
    ports:
      - "80:80"  # Nginx
    # Sin volúmenes en producción

  back-end:
    volumes: []  # Elimina volúmenes en producción